sudo: required

services:
  - docker

before_install:
  - docker build -t hej566/complex-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true hej566/complex-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-732146629051'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
